# version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network


  backend:
    build:
      context: ./backend
    # command: gunicorn auth_site.wsgi --bind 0.0.0.0:8000
    # command: sh /django/entrypoint.sh
    # image: vishnumdev/backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static_volume:/django/staticfiles
      - media_files:/django/media
    env_file:
      - ./backend/.env
    environment:
      DJANGO_SETTINGS_MODULE: auth_site.settings
    networks:
      - backend-network
    links:
      - db:db

  # frontend:
  #   build:
  #     context: ./frontend/client
  #   # image: vishnumdev/frontend:latest
  #   volumes:
  #     - react_build:/client/build
  #   depends_on:
  #     - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      # - react_build:/var/www/client
      - static_volume:/var/www/static
      - media_files:/var/www/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - backend
      - db
      # - frontend
    networks:
      - backend-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - backend-network

volumes:
  # react_build:
  static_volume:
  media_files:
  db_data:
  backup:
  postgres-data:

networks:
  backend-network:
