# version: '3.8'

services:
  backend:
    build:
      context: ./backend
    # command: gunicorn auth_site.wsgi --bind 0.0.0.0:8000
    # command: sh /django/entrypoint.sh
    # image: vishnumdev/backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static_volume:/django/staticfiles
      - media_files:/django/media
    env_file:
      - ./backend/.env
    environment:
      DJANGO_SETTINGS_MODULE: auth_site.settings

  # frontend:
  #   build:
  #     context: ./frontend/client
  #   # image: vishnumdev/frontend:latest
  #   volumes:
  #     - react_build:/client/build
  #   depends_on:
  #     - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      # - react_build:/var/www/client
      - static_volume:/var/www/static
      - media_files:/var/www/media
    depends_on:
      - backend
      # - frontend
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      # - ./backup:/docker-entrypoint-initdb.d
    # entrypoint: /docker-entrypoint-initdb.d/import_database.sh
    container_name: postgres_db
    # ports:
    #   - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  # react_build:
  static_volume:
  media_files:
  db_data:
  backup: