# Generated by Django 5.0.3 on 2024-05-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="seen",
            field=models.BooleanField(default=False),
        ),
    ]
