# Generated by Django 5.0.3 on 2024-05-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_chatmessage_data_chatmessage_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="data",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(blank=True, upload_to="chat/images"),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="media_file",
            field=models.FileField(blank=True, upload_to="chat/media"),
        ),
    ]
