# Generated by Django 5.0.3 on 2024-03-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_profile_age_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile/images"),
        ),
    ]
