# Generated by Django 5.0.3 on 2024-04-05 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_useraccount_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useraccount",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
