# Generated by Django 5.0.3 on 2024-04-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_useraccount_created_at_useraccount_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="is_trainer",
            field=models.BooleanField(default=False),
        ),
    ]
