# Generated by Django 5.0.3 on 2024-04-23 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness_program", "0004_alter_lesson_program"),
        ("user", "0006_useraccount_is_trainer"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowedPrograms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program",
                    models.ManyToManyField(
                        related_name="followers", to="fitness_program.fitnessprogram"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
