# Generated by Django 5.0.3 on 2024-04-24 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_followedprograms"),
    ]

    operations = [
        migrations.AddField(
            model_name="followedprograms",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="followedprograms",
            name="status",
            field=models.CharField(default="Active", max_length=50),
        ),
    ]
