# Generated by Django 5.0.3 on 2024-04-24 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_followedprograms_created_on_followedprograms_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followedprograms",
            name="created_on",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
