# Generated by Django 5.0.3 on 2024-05-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_useraccount_logged_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="online_user_ids",
            field=models.JSONField(default=list),
        ),
    ]
