# Generated by Django 5.0.3 on 2024-05-16 06:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness_program", "0007_fitnessprogram_price"),
        ("user", "0011_profile_online_user_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramFollowers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateField(default=django.utils.timezone.now)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_followers",
                        to="fitness_program.fitnessprogram",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed_fitness_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("program", "user")},
            },
        ),
    ]
