# Generated by Django 5.0.3 on 2024-05-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_delete_programfollowers"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="blocked",
            field=models.BooleanField(default=False),
        ),
    ]
