# Generated by Django 5.0.3 on 2024-04-10 08:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trainer", "0003_alter_trainer_profile_specalized"),
    ]

    operations = [
        migrations.CreateModel(
            name="FitnessProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("duration", models.PositiveIntegerField(help_text="Duration in days")),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="fitness_programs/images"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Cardio", "Cardio"),
                            ("Strength Training", "Strength Training"),
                            ("Yoga", "Yoga"),
                            ("Pilates", "Pilates"),
                            ("HIIT", "HIIT"),
                            ("CrossFit", "CrossFit"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainer.trainer_profile",
                    ),
                ),
            ],
        ),
    ]
