# Generated by Django 5.0.3 on 2024-04-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness_program", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessprogram",
            name="level",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advance", "Advance"),
                ],
                default="Beginner",
                max_length=50,
            ),
        ),
    ]
