# Generated by Django 5.0.3 on 2024-04-16 13:16

import django.db.models.deletion
import fitness_program.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness_program", "0002_fitnessprogram_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitnessprogram",
            name="category",
            field=models.CharField(
                choices=[
                    ("Cardio", "Cardio"),
                    ("Weight Loss", "Weight Loss"),
                    ("Strength Training", "Strength Training"),
                    ("Yoga", "Yoga"),
                    ("Pilates", "Pilates"),
                    ("HIIT", "HIIT"),
                    ("CrossFit", "CrossFit"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="fitness_programs/lessons"
                    ),
                ),
                ("description", models.TextField()),
                (
                    "video_url",
                    models.URLField(
                        validators=[fitness_program.models.validate_youtube_url]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson",
                        to="fitness_program.fitnessprogram",
                    ),
                ),
            ],
        ),
    ]
