# Generated by Django 5.0.3 on 2024-04-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness_program", "0005_lesson_lesson_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="lesson_number",
            field=models.CharField(unique=True),
        ),
    ]
