# Generated by Django 5.0.3 on 2024-05-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness_program", "0006_alter_lesson_lesson_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessprogram",
            name="price",
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
