# Generated by Django 5.0.3 on 2024-05-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness_program", "0007_fitnessprogram_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessprogram",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
