FROM nginx:latest

# Install curl
RUN apt-get update && apt-get install -y curl

# Copy your custom Nginx configuration file
COPY nginx-setup.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80


















# FROM nginx:latest

# # Copy your custom Nginx configuration file
# COPY nginx-setup.conf /etc/nginx/conf.d/default.conf

# # Expose port 80
# EXPOSE 80