# Generated by Django 5.0.3 on 2024-04-09 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trainer_profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specalized",
                    models.CharField(
                        choices=[
                            ("General_fitness", "General_fitness"),
                            ("yoga", "Yoga"),
                            ("meditation", "Meditation"),
                            ("diet", "Diet"),
                            ("calisthenics", "Calisthenics"),
                            ("weight_training", "Weight Training"),
                            ("Cardio", "Cardio"),
                            ("Other", "Other"),
                        ],
                        default="General_fitness",
                        max_length=50,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("about", models.CharField(blank=True, max_length=700, null=True)),
                (
                    "certifications",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
