# Generated by Django 5.0.3 on 2024-04-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trainer", "0002_trainer_profile_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer_profile",
            name="specalized",
            field=models.CharField(default="General_fitness", max_length=50),
        ),
    ]
