# Generated by Django 5.0.3 on 2024-04-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trainer", "0003_alter_trainer_profile_specalized"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer_profile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="trainer/images"),
        ),
    ]
